"""Build the native client's fallback tables from the world; --check verifies them."""

import json
import sys

from ap_env import REPOSITORY_ROOT, archipelago_root, link_world, missing_checkout_message


def main() -> int:
    root = archipelago_root()
    if root is None:
        raise RuntimeError(missing_checkout_message())
    if link_world(root) is None:
        return 1
    sys.path.insert(0, str(root))
    from worlds.gta_vice_city import data, items, locations
    from worlds.gta_vice_city.check_markers import check_markers

    tables = {
        "markers": check_markers(dict.fromkeys(locations.CLASS_TOGGLE.values(), True)),
        "items": {str(item_id): [name, int(items.ITEM_CLASSIFICATIONS[name])]
                  for name, item_id in items.ITEM_NAME_TO_ID.items()},
        "locations": {str(location_id): name for name, location_id in locations.LOCATION_NAME_TO_ID.items()},
        "strands": [[strand, items.ITEM_NAME_TO_ID[data.progressive_item_name(strand)],
                     data.progressive_item_count(strand), strand in data.VENUE_STRANDS]
                    for strand in [*data.STORY_GIVERS, *data.VENUE_STRANDS]],
    }
    encoded = json.dumps(tables, ensure_ascii=True, separators=(",", ":"))
    # MSVC limits individual string literals; adjacent literals concatenate.
    content = ("// Generated by scripts/build_native_data.py.\n#pragma once\n"
               "namespace gtavc {\ninline constexpr char kNativeData[] =\n"
               + "\n".join('R"APDATA(' + encoded[start:start + 8000] + ')APDATA"'
                           for start in range(0, len(encoded), 8000))
               + ";\n}\n")
    target = REPOSITORY_ROOT / "mod/asi/src/native_data.hpp"
    if "--check" in sys.argv:
        return int(target.read_text(encoding="utf-8") != content)
    target.write_text(content, encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main())
