"""Generate the ambient pickup table from a clean VC decompile.

The randomize_pickups option permutes the ambient world pickups: street
weapons, health hearts, body armors, adrenaline pills, and police bribes.
This scanner extracts their placements into pickup_data.py. The eligible
sites are exactly:

- the #BRIBE creations in the MAIN section (every other allowlisted MAIN
  creation is a safehouse package reward the APREWD watcher re-gates), and
- every allowlisted creation in the Mission 0 block, the init mission that
  places the ambient world items at a new game.

Mission-created pickups elsewhere stay vanilla, so every other block is
ignored. Lines with variable operands are mission logic and never match.

The decompile is the player's own, generated locally and never committed, so
run this against the clean.txt produced for the SCM build. The emitted
module holds only coordinates and ids, like package_data.py.

Usage:
    python scripts/dump_pickups.py path/to/clean.txt apworld/gta_vice_city/pickup_data.py
"""

from __future__ import annotations

import math
import re
import sys

MISSION_HEADER = re.compile(r"^//-------------Mission (\d+)---------------$")
CREATE_PICKUP = re.compile(
    r"^create_pickup \$\w+ = create_pickup (#\w+|\d+) type (\d+)"
    r" at (-?\d+(?:\.\d+)?) (-?\d+(?:\.\d+)?) (-?\d+(?:\.\d+)?)$")
CREATE_WEAPON_PICKUP = re.compile(
    r"^create_pickup_with_ammo \$\w+ = create_weapon_pickup (\d+) (\d+) ammo (\d+)"
    r" at (-?\d+(?:\.\d+)?) (-?\d+(?:\.\d+)?) (-?\d+(?:\.\d+)?)$")

NAMED_MODELS = {"#HEALTH": 366, "#ADRENALINE": 367, "#BODYARMOUR": 368, "#BRIBE": 375}
WEAPON_MODEL_FIRST = 259
WEAPON_MODEL_LAST = 291
MINIMUM_SLOT_SEPARATION = 1.5

MODEL_NAMES = {
    259: "Brass Knuckles",
    260: "Screwdriver",
    261: "Golf Club",
    262: "Nightstick",
    263: "Knife",
    264: "Baseball Bat",
    265: "Hammer",
    266: "Meat Cleaver",
    267: "Machete",
    268: "Katana",
    269: "Chainsaw",
    270: "Grenades",
    271: "Tear Gas",
    272: "Molotov Cocktails",
    274: "Colt .45",
    275: ".357",
    276: "Ruger",
    277: "Chrome Shotgun",
    278: "S.P.A.S. 12",
    279: "Stubby Shotgun",
    280: "M4",
    281: "Tec-9",
    282: "Uzi",
    283: "Ingram Mac 10",
    284: "MP5",
    285: "Sniper Rifle",
    286: ".308 Sniper",
    287: "Rocket Launcher",
    288: "Flamethrower",
    289: "M60",
    290: "Minigun",
    291: "Detonator Grenades",
    366: "Health",
    367: "Adrenaline",
    368: "Body Armor",
    375: "Police Bribe",
}

MODULE_DOCSTRING = '''"""Ambient pickup data, generated by scripts/dump_pickups.py.

Each row is one eligible world pickup slot in decompile order:
(x, y, z, pickup type, vanilla model, vanilla ammo). The randomize_pickups
option permutes the (model, ammo) pairs across the slots; the position and
the pickup type stay with the slot. Type 1 is the in-shop type whose cost
lookup misreads on the bribe model, so bribes never land on type 1 slots.
"""'''


def parse_model(token: str) -> int | None:
    if token in NAMED_MODELS:
        return NAMED_MODELS[token]
    if token.startswith("#"):
        return None
    model = int(token)
    if WEAPON_MODEL_FIRST <= model <= WEAPON_MODEL_LAST:
        return model
    return None


def extract(lines: list[str]) -> list[tuple[float, float, float, int, int, int]]:
    headers = [(int(MISSION_HEADER.match(line).group(1)), index)
               for index, line in enumerate(lines) if MISSION_HEADER.match(line)]
    boundaries = dict(headers)
    mission_zero_start = boundaries[0]
    mission_zero_end = boundaries[1]

    slots: list[tuple[float, float, float, int, int, int]] = []
    for index, raw_line in enumerate(lines):
        line = raw_line.strip()
        in_main = index < mission_zero_start
        in_mission_zero = mission_zero_start <= index < mission_zero_end
        if not in_main and not in_mission_zero:
            continue

        plain = CREATE_PICKUP.match(line)
        if plain:
            model = parse_model(plain.group(1))
            if model is None:
                continue
            if in_main and plain.group(1) != "#BRIBE":
                continue
            slots.append((float(plain.group(3)), float(plain.group(4)),
                          float(plain.group(5)), int(plain.group(2)), model, 0))
            continue

        if in_main:
            continue
        weapon = CREATE_WEAPON_PICKUP.match(line)
        if weapon:
            slots.append((float(weapon.group(4)), float(weapon.group(5)),
                          float(weapon.group(6)), int(weapon.group(2)),
                          int(weapon.group(1)), int(weapon.group(3))))
    return slots


def check_separation(slots: list[tuple[float, float, float, int, int, int]]) -> float:
    minimum = math.inf
    for first in range(len(slots)):
        for second in range(first + 1, len(slots)):
            distance = math.dist(slots[first][:3], slots[second][:3])
            minimum = min(minimum, distance)
    return minimum


def render_module(slots: list[tuple[float, float, float, int, int, int]]) -> str:
    lines = [MODULE_DOCSTRING, "", "from __future__ import annotations", ""]
    lines.append("PICKUP_SLOTS: list[tuple[float, float, float, int, int, int]] = [")
    for x, y, z, pickup_type, model, ammo in slots:
        lines.append(f"    ({x}, {y}, {z}, {pickup_type}, {model}, {ammo}),")
    lines.append("]")
    lines.append("")
    lines.append("PICKUP_MODEL_NAMES: dict[int, str] = {")
    lines.extend(f'    {model}: "{MODEL_NAMES[model]}",'
                 for model in sorted({slot[4] for slot in slots}))
    lines.append("}")
    lines.append("")
    lines.append("BRIBE_MODEL = 375")
    lines.append("SHOP_PICKUP_TYPE = 1")
    lines.append("")
    return "\n".join(lines)


def main(source_path: str, output_path: str) -> int:
    with open(source_path, "rb") as handle:
        raw = handle.read()
    newline = "\r\n" if b"\r\n" in raw else "\n"
    lines = raw.decode("latin-1").split(newline)

    slots = extract(lines)
    separation = check_separation(slots)
    families: dict[str, int] = {}
    for slot in slots:
        name = MODEL_NAMES[slot[4]]
        family = name if slot[4] >= 366 else "Weapon"
        families[family] = families.get(family, 0) + 1
    print(f"# {len(slots)} slots, families {families}, "
          f"closest pair {separation:.2f} units", file=sys.stderr)
    if separation < MINIMUM_SLOT_SEPARATION:
        print("# pair closer than the matching tolerance allows, refusing",
              file=sys.stderr)
        return 1

    with open(output_path, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(render_module(slots))
    return 0


if __name__ == "__main__":
    if len(sys.argv) != 3:
        print(__doc__, file=sys.stderr)
        raise SystemExit(2)
    raise SystemExit(main(sys.argv[1], sys.argv[2]))
